In [3]:
import numpy
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
m = numpy.asarray([[123,13,23,123,23],[],[]])
m

array([list([123, 13, 23, 123, 23]), list([]), list([])], dtype=object)

In [14]:
import cv2
import os
os.listdir()

['.ipynb_checkpoints', 'Numpy Arrays.ipynb', 'smallgray.png']

In [17]:
im_g = cv2.imread("smallgray.png", 1)
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [19]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [21]:
im_g2 = cv2.imread("smallgray.png", 0)
im_g2

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
im_g2[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [27]:
im_g2.shape

(3, 5)

In [29]:
#iterate through rows
for i in im_g2:
    print(i) #i is for a row

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [31]:
#iterating columns need to use Transposition
for c in im_g2.T:
    print(c) #c is for a column

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [33]:
#itarating values separetely
for i in im_g2.flat:
    print(i) #i for a separete value

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [38]:
ins = numpy.hstack((im_g2, im_g2)) #it can accept only one argument so if we need to stack two and more arrays we use tuple
ins

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [40]:
ins = numpy.vstack((im_g2, im_g2))
ins

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [42]:
spims = numpy.hsplit(ins,5)
spims

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [44]:
spims = numpy.vsplit(ins, 2)
spims

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]